package apply

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/matheme/pkg"
)

// hexRGBToBGR converts a "#RRGGBB" color to squirrel's "0xBBGGRR" format.
func hexRGBToBGR(hex string) string {
	hex = strings.TrimPrefix(hex, "#")
	if len(hex) != 6 {
		return "0xFFFFFF"
	}
	return fmt.Sprintf("0x%s%s%s", hex[4:6], hex[2:4], hex[0:2])
}

// hilitedTextColor picks the candidate text color on the base0D accent.
// dark theme: base00 (deep) on light accent; light theme: base07 (deep) on light accent.
func hilitedTextColor(theme *pkg.Theme) string {
	if theme.Type == "light" {
		return theme.Base16["base07"]
	}
	return theme.Base16["base00"]
}

// ApplyRimeTheme writes a matheme color scheme file for squirrel (Rime on macOS).
// The generated file is included by squirrel.custom.yaml via __include.
func ApplyRimeTheme(theme *pkg.Theme, rimeDir string) (string, error) {
	if rimeDir == "" {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get user home directory: %w", err)
		}
		rimeDir = filepath.Join(homeDir, "Library", "Rime")
	}

	ht := hilitedTextColor(theme)

	content := fmt.Sprintf(`# Auto-generated by matheme. Do not edit manually.
preset_color_schemes:
  matheme:
    name: "matheme"
    author: matheme
    color_space: srgb
    back_color: %s
    border_color: %s
    text_color: %s
    hilited_back_color: %s
    candidate_text_color: %s
    hilited_candidate_back_color: %s
    hilited_candidate_text_color: %s
    hilited_candidate_label_color: %s
    label_color: %s
    hilited_text_color: %s
    hilited_comment_text_color: %s
    comment_text_color: %s
`,
		hexRGBToBGR(theme.Base16["base00"]),
		hexRGBToBGR(theme.Base16["base01"]),
		hexRGBToBGR(theme.Base16["base05"]),
		hexRGBToBGR(theme.Base16["base01"]),
		hexRGBToBGR(theme.Base16["base05"]),
		hexRGBToBGR(theme.Base16["base0D"]),
		hexRGBToBGR(ht),
		hexRGBToBGR(ht),
		hexRGBToBGR(theme.Base16["base03"]),
		hexRGBToBGR(theme.Base16["base0D"]),
		hexRGBToBGR(theme.Base16["base04"]),
		hexRGBToBGR(theme.Base16["base03"]),
	)

	if err := os.MkdirAll(rimeDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create rime config directory: %w", err)
	}

	dst := filepath.Join(rimeDir, "matheme_squirrel.yaml")
	if err := os.WriteFile(dst, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write rime theme file: %w", err)
	}

	return dst, nil
}

// ReloadSquirrel triggers an async redeploy of squirrel to apply config changes.
func ReloadSquirrel() error {
	squirrelBin := "/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel"
	if _, err := os.Stat(squirrelBin); err != nil {
		return fmt.Errorf("squirrel binary not found at %s: %w", squirrelBin, err)
	}
	return exec.Command(squirrelBin, "--reload").Run()
}
